spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wcb 
      
server:
  port: 8080

management:
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - mappings
 
